import React, { useState, useEffect } from 'react';
import { 
  CreditCard, 
  Search, 
  Download, 
  Printer, 
  Plus, 
  AlertCircle,
  FileText,
  DollarSign
} from 'lucide-react';
import { collection, addDoc, getDocs, query, orderBy, Timestamp, limit } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Transaction } from '../types';
import { formatDate, formatCurrency, cn } from '../lib/utils';
import { motion, AnimatePresence } from 'motion/react';

export default function Fees() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [isCollectModalOpen, setIsCollectModalOpen] = useState(false);

  // New Transaction Form
  const [newTx, setNewTx] = useState({
    memberId: '',
    memberName: '',
    amount: 0,
    paymentType: 'Cash',
    transactionType: 'Monthly Fee',
    month: new Date().toLocaleString('default', { month: 'long' }),
    year: new Date().getFullYear(),
    branchId: 'Main Branch'
  });

  useEffect(() => {
    fetchTransactions();
  }, []);

  const fetchTransactions = async () => {
    setLoading(true);
    try {
      const q = query(collection(db, 'transactions'), orderBy('date', 'desc'), limit(50));
      const snapshot = await getDocs(q);
      const list = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })) as Transaction[];
      setTransactions(list);
    } catch (error) {
      console.error("Error fetching transactions:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleCollectFee = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const receiptId = `REC-${Date.now().toString().slice(-6)}`;
      await addDoc(collection(db, 'transactions'), {
        ...newTx,
        receiptId,
        date: Timestamp.now(),
      });
      setIsCollectModalOpen(false);
      fetchTransactions();
    } catch (error) {
      console.error("Error collecting fee:", error);
    }
  };

  const handlePrint = (tx: Transaction) => {
    const printContent = `
      <html>
        <head>
          <title>Fee Receipt - ${tx.receiptId}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; }
            .content { margin-top: 30px; }
            .row { display: flex; justify-content: space-between; margin: 10px 0; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
            .stamp { border: 2px solid #000; padding: 10px; width: 100px; text-align: center; margin-top: 20px; opacity: 0.3; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>PAK GYM PRO</h1>
            <p>DHA Phase 6, Lahore | 042-xxxxxxx</p>
            <h3>PAYMENT RECEIPT</h3>
          </div>
          <div class="content">
            <div class="row"><strong>Receipt ID:</strong> <span>${tx.receiptId}</span></div>
            <div class="row"><strong>Date:</strong> <span>${formatDate(tx.date)}</span></div>
            <div class="row"><strong>Member:</strong> <span>${tx.memberName}</span></div>
            <div class="row"><strong>For Month:</strong> <span>${tx.month} ${tx.year}</span></div>
            <div class="row"><strong>Payment Mode:</strong> <span>${tx.paymentType}</span></div>
            <div class="row"><strong>Type:</strong> <span>${tx.transactionType}</span></div>
            <hr />
            <div class="row" style="font-size: 20px; font-weight: bold;">
              <strong>Total Amount:</strong> 
              <span>${formatCurrency(tx.amount)}</span>
            </div>
          </div>
          <div class="stamp">PAID</div>
          <div class="footer">
            <p>Generated by PakGym Management System</p>
            <p>Computer generated receipt, no signature required.</p>
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `;
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
    }
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Fee Ledger</h2>
          <p className="text-zinc-500 mt-1">Track payments, collection history and overdue dues.</p>
        </div>
        <button 
          onClick={() => setIsCollectModalOpen(true)}
          className="flex items-center gap-2 bg-white text-black px-6 py-3 rounded-2xl font-bold hover:bg-zinc-200 transition-all active:scale-[0.98]"
        >
          <Plus className="w-5 h-5" />
          Collect Fee
        </button>
      </header>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="p-6 bg-zinc-900 border border-zinc-800 rounded-3xl">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-zinc-800 rounded-2xl">
              <DollarSign className="w-6 h-6 text-green-500" />
            </div>
            <div>
              <p className="text-xs text-zinc-500 font-bold uppercase">This Month</p>
              <h3 className="text-2xl font-bold">{formatCurrency(450000)}</h3>
            </div>
          </div>
          <p className="text-xs text-zinc-600">85% of target collected</p>
        </div>
        <div className="p-6 bg-zinc-900 border border-zinc-800 rounded-3xl">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-zinc-800 rounded-2xl text-orange-500">
              <AlertCircle className="w-6 h-6" />
            </div>
            <div>
              <p className="text-xs text-zinc-500 font-bold uppercase">Overdue</p>
              <h3 className="text-2xl font-bold">14 Members</h3>
            </div>
          </div>
          <p className="text-xs text-zinc-600">Totaling Rs. 42,000</p>
        </div>
        <div className="p-6 bg-zinc-900 border border-zinc-800 rounded-3xl">
          <div className="flex items-center gap-4 mb-4">
            <div className="p-3 bg-zinc-800 rounded-2xl text-blue-500">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <p className="text-xs text-zinc-500 font-bold uppercase">Transactions</p>
              <h3 className="text-2xl font-bold">156</h3>
            </div>
          </div>
          <p className="text-xs text-zinc-600">Last updated today</p>
        </div>
      </div>

      {/* Transactions Table */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-3xl overflow-hidden">
        <div className="p-6 border-b border-zinc-800 flex items-center justify-between">
          <h3 className="font-bold">Recent History</h3>
          <div className="flex gap-2">
             <button className="p-2 bg-zinc-800 rounded-lg hover:bg-zinc-700 transition-colors">
               <Download className="w-4 h-4" />
             </button>
             <button className="p-2 bg-zinc-800 rounded-lg hover:bg-zinc-700 transition-colors">
               <Search className="w-4 h-4" />
             </button>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-zinc-800">
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">ID</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">Member</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">Amount</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">For Month</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">Type</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500">Date</th>
                <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-zinc-500 text-right">Receipt</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-800">
              {loading ? (
                <tr><td colSpan={7} className="px-6 py-12 text-center text-zinc-500">Loading ledger...</td></tr>
              ) : transactions.length === 0 ? (
                <tr><td colSpan={7} className="px-6 py-12 text-center text-zinc-500">No transactions recorded.</td></tr>
              ) : transactions.map((tx) => (
                <tr key={tx.id} className="hover:bg-zinc-800/50 transition-colors">
                  <td className="px-6 py-4 text-sm font-mono text-zinc-500">{tx.receiptId}</td>
                  <td className="px-6 py-4 font-bold">{tx.memberName}</td>
                  <td className="px-6 py-4 font-bold text-green-500">{formatCurrency(tx.amount)}</td>
                  <td className="px-6 py-4 text-sm">{tx.month} {tx.year}</td>
                  <td className="px-6 py-4">
                    <span className="bg-zinc-800 px-2 py-1 rounded-lg text-[10px] font-bold uppercase">
                      {tx.transactionType}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-zinc-500">{formatDate(tx.date)}</td>
                  <td className="px-6 py-4 text-right">
                    <button 
                      onClick={() => handlePrint(tx)}
                      className="p-2 hover:bg-zinc-700 rounded-lg transition-colors text-zinc-400 hover:text-white"
                    >
                      <Printer className="w-5 h-5" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Collect Fee Modal */}
      <AnimatePresence>
        {isCollectModalOpen && (
          <div className="fixed inset-0 flex items-center justify-center z-50 p-4">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm"
              onClick={() => setIsCollectModalOpen(false)}
            />
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="relative w-full max-w-lg bg-zinc-900 border border-zinc-800 rounded-3xl p-8"
            >
              <h3 className="text-2xl font-bold mb-6">Collect Fee</h3>
              <form onSubmit={handleCollectFee} className="space-y-4">
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase text-zinc-500">Search Member</label>
                  <input 
                    required
                    type="text"
                    placeholder="Enter full name..."
                    value={newTx.memberName}
                    onChange={(e) => setNewTx({...newTx, memberName: e.target.value})}
                    className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-white/20"
                  />
                  <input 
                    required
                    type="hidden"
                    value={newTx.memberId}
                  />
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase text-zinc-500">Amount (PKR)</label>
                    <input 
                      required
                      type="number"
                      value={newTx.amount}
                      onChange={(e) => setNewTx({...newTx, amount: Number(e.target.value)})}
                      className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-white/20"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase text-zinc-500">Mode</label>
                    <select 
                      value={newTx.paymentType}
                      onChange={(e) => setNewTx({...newTx, paymentType: e.target.value as any})}
                      className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 outline-none"
                    >
                      <option>Cash</option>
                      <option>Online</option>
                      <option>Bank Transfer</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase text-zinc-500">Month</label>
                    <select 
                      value={newTx.month}
                      onChange={(e) => setNewTx({...newTx, month: e.target.value})}
                      className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 outline-none"
                    >
                      {['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map(m => (
                        <option key={m}>{m}</option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase text-zinc-500">Transaction Category</label>
                    <select 
                       value={newTx.transactionType}
                       onChange={(e) => setNewTx({...newTx, transactionType: e.target.value as any})}
                       className="w-full bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 outline-none"
                    >
                      <option>Monthly Fee</option>
                      <option>Admission</option>
                      <option>Personal Training</option>
                    </select>
                  </div>
                </div>

                <button 
                  type="submit"
                  className="w-full bg-white text-black py-4 rounded-xl font-bold mt-4 hover:bg-zinc-200 transition-all active:scale-[0.98]"
                >
                  Confirm & Generate Receipt
                </button>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
